### ISSUE TITLE
Library Launch Roadmap

### ISSUE THREAD

**Issue by Zmoki** [uploadcare/uploadcare-upload-client#9]
**Target**: launch a production-ready package

### Alpha 0

* Support of following Uploadcare Settings:
  * [x] `publicKey`,
  * [x] `baseUrl`, 
  * [x] `doNotStore`,
  * [x] `integration`, 
  * [x] `userAgent`,
  * [x] `secureExpire`,
  * [x] `secureSignature`
* [x] The `request` function to request to any path of Upload API 
  * [x] with the support of Uploadcare Settings
* [x] A function to run upload request to Upload API, with progress and cancel, with the support of Uploadcare Settings
* [x] Exporting both `UploadcareUpload` class and individual functions (useful for tree shaking)
* [x] Set up Uploadcare Settings as function‘s parameter and as in constructor and special method of `UploadcareUpload` class for changing settings in any way
* [x] Wrappers for following paths of Upload API: `base`, `info`
* [x] The high-level function like `filesFrom` only with the support of direct uploads (`base`) yet

### Alpha 1

* [x] Use package version in getUserAgent
* [x] ~~Add on/off methods~~ Make uploading thenable

### Alpha 2
* [x] The support of url uploads in `fileFrom`
* [x] Low-level request wrappers for `/from_url/` and `/from_url/status/` paths of Upload API.
* [x] Settings: the support of setting `baseCDN`, `checkForUrlDuplicates`, `saveUrlForRecurrentUploads`.

### Alpha 3

* [x] Add support of upload file from uploaded in `fileFrom`
* [x] Add throttling to API requests

### Alpha 4

* [x] Wrappers for group paths of Upload API
* [x] Add uploading progress for Node.js in `base` method
* [x] The high-level function for group uploading, aka filesGroupFrom

### Alpha 5

* [x] Support of multipart and uploading of big files

### Alpha 6

* [ ] Use user feedback from alpha program
* [ ] Support of next following Uploadcare Settings: pusherKey (?), debug
* [ ] Contribution guide

Next, we will fix bugs, structure, and naming, if needed, and prepare the library for production release.
